### PR TITLE
Implementation of public boolean delete(User usr), public User findUs…

### PR DESCRIPTION
**Pull request by salineroalex**
Hello,

As agreed in the meeting, I'm creating the pull request for branches User Controllable 1 and 2.

Please, review and comment any issues you see.

### CODE REVIEW

**Comment by iratigarzon** [comment]
Hello,

After resolving the conflicts, it appears that the code is correct.

**Comment by iblanco-s** [comment]
hi, 
looks good to me, go ahead

**Comment by Javier-Fermin** [comment]
Hey,
After solvinf the conflict everything seems perfect

**Comment by salineroalex** [comment]
Ok, I'm merging

**Pull request merged**
