### PR TITLE
Creation of champ Player and champ Admin tabs

### PR DESCRIPTION
**Pull request by iblanco-s**
Hi, im asking to merge my branch where both champ tabs were developed with devGUI

### CODE REVIEW

**Comment by iblanco-s** [comment]
I solved the conflict, check that it is right and give me the approval, ty

**Comment by iratigarzon** [comment]
Okay, I see that you solved the conflict and it looks okay! Go ahead!

**Comment by salineroalex** [comment]
Conflict looks solved, okay to merge

**Comment by Javier-Fermin** [comment]
Everything seems to be okay after the conflict has been solved so I approve with the merge

**Pull request merged**
