### PR TITLE
Dev user controllable db implementation1

### PR DESCRIPTION
**Pull request by iratigarzon**
Hello, 

I make the pull request to merge the devUserControllableDBImplementation to the devContoller.

Please check if everything is okay.

Thank you!

### CODE REVIEW

**Comment by Javier-Fermin** [comment]
Hello,

For me you can go ahead I don't have any problem with your code

**Comment by iblanco-s** [comment]
perfect, go ahead

**Comment by salineroalex** [comment]
No errors, go ahead :)

**Comment by iratigarzon** [comment]
Okay, thank you!

**Pull request merged**
